version: "3.8"
services:
    grocy:
        image: linuxserver/grocy
        container_name: grocy
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Colombo
        volumes:
            - /home/bisina/Docker/grocy/config:/config
        networks:
            - bisinet_main
        ports:
            - 8004:80
        healthcheck:
            test: curl --fail -s http://10.10.10.100:8004/ || exit 1
            interval: 30s
            timeout: 10s
            retries: 3
        restart: unless-stopped


    mysql-snipit:
        image: mysql:5.7.30
        container_name: snipe_mysql
        environment:
            - MYSQL_ROOT_PASSWORD=nath500@
            - MYSQL_USER=snipe
            - MYSQL_PASSWORD=nath500@
            - MYSQL_DATABASE=snipe
        volumes:
            - /home/bisina/Docker/mysql_snipit:/var/lib/mysql
        networks:
            - bisinet_main
        ports:
            - 3307:3306
        healthcheck:
            test: "/usr/bin/mysql --user=snipe --password=nath500@ --execute \"SHOW DATABASES;\""
            interval: 30s
            timeout: 10s
            retries: 5
        restart: always
        

    snipeit:
        image: linuxserver/snipe-it:latest
        container_name: snipe-it
        depends_on:
            - mysql-snipit
        environment:
            - APP_URL=10.10.10.100:8005
            - MYSQL_PORT_3306_TCP_ADDR=10.10.10.100
            - MYSQL_PORT_3306_TCP_PORT=3307
            - MYSQL_DATABASE=snipe
            - MYSQL_USER=snipe
            - MYSQL_PASSWORD=nath500@
            - PGID=1000
            - PUID=1000
        volumes:
            - /home/bisina/Docker/snipit/config:/config
        networks:
            - bisinet_main
        ports:
        - "8005:80"
        healthcheck:
            test: curl --fail -s http://10.10.10.100:8005/ || exit 1
            interval: 30s
            timeout: 10s
            retries: 3
        restart: unless-stopped

networks:
    bisinet_main:
        driver: bridge
        external: true
        name: bisinet

    