version: "3.8"

services:
  gotify:
    image: gotify/server
    container_name: gotify
    environment:
      - GOTIFY_DEFAULTUSER_NAME=bisina
      - GOTIFY_DEFAULTUSER_PASS=nath500@
      - TZ=Asia/Colombo
    volumes:
      - /home/bisina/Docker/gotify/data:/app/data
    networks:
            - bisinet_main
    ports:
        - 8080:80
    healthcheck:
        test: curl --fail -s http://10.10.10.134:8080 || exit 1
        interval: 60s
        timeout: 60s
        retries: 3
    restart: unless-stopped

networks:
    bisinet_main:
        driver: bridge
        external: true
        name: bisinet