global:
    scrape_interval: 5s
    external_labels:
        monitor: 'bisinet-monitor'
scrape_configs:
    - job_name: 'prometheus'
      static_configs:
        - targets: ['10.10.10.135:9090']
    - job_name: 'node-exporter'
      static_configs:
        - targets: ['10.10.10.135:9100','10.10.10.134:9100']
    - job_name: 'cAdvisor'
      static_configs:
        - targets: ['10.10.10.135:8080','10.10.10.134:8090']

